### PR TITLE
various suggestions

### PR DESCRIPTION
**Pull request by rhijmans**
Here are few proposed changes for your consideration.

- Allow the use SpatVector or SpatRaster to set the area of interest

- fix Rd link to tempdir 

- use gdal() instead of the obsolete gdal_version (I also think you can now lower the required GDAL version to what terra uses)

- use "smooth" instead of the obsolete "interpolate" as argument to plotRGB

- use "RGB<-" such that terra::plot calls plotRGB, illustrated below

library(terra)
library(maptiles)
f <- system.file("ex/lux.shp", package="terra")
v <- vect(f)
g <- get_tiles(v)
plot(g)

### CODE REVIEW

**Comment by rCarto** [comment]
Thank you !

**Comment by rCarto** [comment]
>     * use gdal() instead of the obsolete gdal_version (I also think you can now lower the required GDAL version to what terra uses)

Hello @rhijmans, 
Does that mean `project`, `resample` and `as.polygons` are working with GDAL (>= 2.2.3)?

**Comment by rhijmans** [comment]
Yes, that is correct.  At least they now work for me with GDAL 2.2.3.

**Comment by rCarto** [comment]
That's perfect, thank you.

**Pull request merged**
